### ISSUE TITLE
Add support to sslcafile and sslcapath to Curl adapter

### ISSUE THREAD

**Issue by mlocati** [zendframework/zend-http#100]
The Socket adapter supports the `sslcafile` and `sslcapath` options.

What about adding support to them in the Curl adapter too (via the `curl_setopt` command with `CURLOPT_CAINFO` and `CURLOPT_CAPATH`)?

**Comment by mlocati** [comment]
Pull request: #97

**Comment by ezimuel** [comment]
#97 is merged.
