### ISSUE TITLE
Cookies class doesn't allow Header\Cookie instances

### ISSUE THREAD

**Issue by noisebleed** [zendframework/zend-http#12]
As opposed to the comment in [Cookies:: addCookie](https://github.com/zendframework/zend-http/blob/release-2.5.1/src/Cookies.php#L91):

> Cookie should be passed either as a Zend\Http\Header\Cookie object or as a string

`Cookies:: addCookie` actually only allow instances of `SetCookie` to be passed as an argument.

The comment is not aligned with the implementation. Which one represents the expected behaviour?

**Comment by weierophinney** [comment]
Considering we test the _code_, the code is correct. Would you please create a PR to update the comment?

**Comment by noisebleed** [comment]
Yes, I will, Thanks @weierophinney.
