### ISSUE TITLE
How to Install zend-http manually?

### ISSUE THREAD

**Issue by Mark-Joy** [zendframework/zend-http#126]
Hello,

My website is on shared hosting server, so I can not install composer and zend-http via composer.
Here are the steps I installed zend-http (my PHP version is 5.6.3. Phpinfo shows Server API :  CGI/FastCGI)

1> Download ZF 2.4.13 from https://framework.zend.com/downloads/archives.
2> Extract it into /pathToZendOnServer. So now I have /pathToZendOnServer/library/Zend/Http on my server
3> Add include_path=/pathToZendOnServer/library:OtherPaths into php.ini
4> Wait for server to update new include_path by running command phpinfo and check if the path is there in include_path.
5> I create a new file with the below contents and run it via browser(chrome). Always get HTTP ERROR 500
Any suggestion to help me solve this issue, please?

```
<?php
use Zend\Http\Client;
require "Zend/Http/Client.php";

$client = new Client('http://google.com');
$response = $client->send();
print_r($reponse);
?>
```

**Comment by Mark-Joy** [comment]
I found [the answer](https://stackoverflow.com/questions/17622637/how-to-load-zend-2-classes-on-autoloader). I need Zend auto loader to load the class. This information can't be seen in a simple example of Zend-Http.

```
require_once 'Zend/Loader/StandardAutoloader.php';
$autoloader = new Zend\Loader\StandardAutoloader(array(
    'fallback_autoloader' => true,
));
$autoloader->register();
```

**Comment by xtreamwayz** [comment]
For questions there is the [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) and the [forums](https://discourse.zendframework.com/).

There is another option: Use composer to install zend-http locally and commit the vendor dir into your repository. Make sure that .gitignore doesn't exclude the vendor dir.
