### ISSUE TITLE
Is this some sort of joke?

### ISSUE THREAD

**Issue by unfunco** [zendframework/zend-http#137]
https://github.com/zendframework/zend-http/blob/b382c6e068a2d9c87b7cf0dfe78c6dd19e4ff197/src/Response.php#L24

**Comment by froschdesign** [comment]
@unfunco 
Help is always welcome and also criticism. But please try to make your request reasonable. (see also: [Code Manifesto](https://framework.zend.com/participate/code-manifesto))

**Comment by Xerkus** [comment]
Sure, why not? We are not against good laugh after all.

**Comment by Ocramius** [comment]
@unfunco yes
