### ISSUE TITLE
cookie values decode error

### ISSUE THREAD

**Issue by malinink** [zendframework/zend-http#15]
Hi!
I have found one problem with encoding.

In PHP it's normal behavior that values are urlencoded, but in other languages there are another standards for encoding such value, for example - in python.

So, cookie created in python could be invalid after urldecode here:
https://github.com/zendframework/zend-http/blob/master/src/Header/SetCookie.php#L119

But if we want to fix that issue, we suppose to get rid of that urlencode also:
https://github.com/zendframework/zend-http/blob/master/src/Header/SetCookie.php#L236

That is wrong, cause when we try to set cookie with specific symbols - we get wrong cookie.

I really don't know how to fix problem, have anyone ideas?

I thought that best approach is to add client type (php, python) and add specific decode/encode functions for each type, also add default type which only encode values.

At now I have a site that causes Zend Http Client failed on send method:

``` php
        $client = new Client('http://www.gd.ru/articles/3514-uvelichenie-prodaj');
        $client->send();
```

**Comment by malinink** [comment]
For example default action may looks like that one.

**Comment by weierophinney** [comment]
@malinink Can you please submit your changes as a pull request?

**Comment by malinink** [comment]
@weierophinney Pull request have been added.

**Comment by zerocrates** [comment]
I mistakenly filed a duplicate issue for this.

I think the best way to distill it down is to post a tiny one-liner that fails when it shouldn't:

```php
Zend\Http\Header\SetCookie::fromString('Set-Cookie:foo=%0A; path=/; HttpOnly');
```

The practical upshot is that any attempt to make a *request* to a server that emits cookies with urlencoded whitespace in the value will fail because the SetCookie header class is urldecoding the value before attempting to validate it.
