### ISSUE TITLE
keepalive/persistent doesn't persist

### ISSUE THREAD

**Issue by rinu** [zendframework/zend-http#150]
Reproducing code

	<?php

	require 'vendor/autoload.php';

	$client = new \Zend\Http\Client('http://example.com', [
		'keepalive' => true,
		'persistent' => true
	]);

	$start = microtime(true);
	$client->send();
	echo microtime(true) - $start . "\n";

	$start = microtime(true);
	$client->send();
	echo microtime(true) - $start . "\n";

When executed, it will output something similar to

	0.22347211837769
	0.11083388328552

This is expected but only on the first execution. On the following executions the previously made connection should persist and the times should be almost identical. It works the same way with CLI and FPM.

I'm using PHP 7.2 and installed zend-http with `composer require zendframework/zend-http`

**Comment by thomasvargiu** [comment]
@rinu why are you expecting the same time?

- on the first request the `Socket` adapter will connect and make the request
- on second request the `Socket` adapter should be still connected and make the 2nd request

So I think it's correct that the 2nd request is faster than the 1st one.

**Comment by rinu** [comment]
What I want is currently not supported by PHP. It can't cache connections between processes.

**Comment by thomasvargiu** [comment]
It's not possible on different processes but it's possible with child process (eg: with apache, php-fpm)

**Comment by Ocramius** [comment]
Closing as inapplicable - not really an issue for zend-http to solve, but rather for the underlying layers.
