### ISSUE TITLE
ContentSecurityPolicy headers overwrite each other

### ISSUE THREAD

**Issue by markushausammann** [zendframework/zend-http#159]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-http/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-http/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

It's often not allowed or recommended to have several headers with the same name. But there are situations where it is allowed or even necessary. The CSP is one of these.

https://w3c.github.io/webappsec-csp/#multiple-policies

and

https://www.w3.org/TR/CSP2/#content-security-policy-header-field

Imagine a case where a main application creates a CSP and different modules also independently add their own CSPs. The framework MUST render them all separately OR do a preemptive union merge which is what the client would otherwise do. It will (hopefully) quickly become standard practice that modules provide their own CSPs.

### Code to reproduce the issue

```php
$headers = $controller->getResponse()->getHeaders();
$headers->addHeader(new ContentSecurityPolicy($someDirectives));
$headers->addHeader(new ContentSecurityPolicy($someOtherDirectives));
```

### Expected results

The expected result is a response with two CSP headers (OR a union merged CSP).

### Actual results

The second addition overwrites the first, the response only contains that one CSP.

**Comment by markushausammann** [comment]
PS: It's not enough to have `ContentSecurityPolicy` implement `MultipleHeaderInterface` I think. The framework also needs to make sure to check for existing policies and append them automatically.

**Comment by markushausammann** [comment]
Am I even in the right repository? Seems this one hasn't really been touched for quite some time.

**Comment by Ocramius** [comment]
Yeah, the repo is correct, but unless someone picks up a failing test case + patch, it's not gonna be solved. If you can manage to create a failing test, that already simplifies things enormously.

**Comment by markushausammann** [comment]
Ok, I'll try to find time for something... not that I'm the right person to do that.

**Comment by Ocramius** [comment]
Yes you are: you know exactly what the bug looks like 👍
