### ISSUE TITLE
A bug fixed on 2.9 but not on 2.8 (Curl Adapter)

### ISSUE THREAD

**Issue by mvatansever** [zendframework/zend-http#171]
Version: 2.8.3
Description: This bug not fixed on 2.8.* minor versions but fixed in 2.9.*

### Code to reproduce the issue

Namespace: Zend\Http\Client\Adapter\Curl
```php
        if ($connectTimeout !== null && (! is_int($connectTimeout) || ! is_numeric($connectTimeout))) {
            throw new AdapterException\InvalidArgumentException(sprintf(
                'integer or numeric string expected, got %s',
                gettype($connectTimeout)
            ));
        }
```

This bug causing on [this](https://github.com/zendframework/zend-http/commit/5b36ca3daf51a02763c409a291f0e7c79b9828cc#diff-3ba15d9b918a4101be3a32eae1034728) commit and fixed on [this](https://github.com/zendframework/zend-http/commit/1c9f2491c88c9a8a3677ed60e6ef8c13d99ff4b6#diff-3ba15d9b918a4101be3a32eae1034728) commit or [this](https://github.com/zendframework/zend-http/commit/a734185344c5c77011272e99b978d139b92605c3#diff-3ba15d9b918a4101be3a32eae1034728) commit. We use 2.8.* version of this package. Can you apply this fix on the 2.8 minor version?

Temporarily we are using 2.8.2 version but the final version(2.8.3) has the bug.

**Comment by Xerkus** [comment]
This project follows [Semantic Versioning](https://semver.org/)
You should upgrade to 2.9, it is backwards compatible to 2.8

**Comment by Xerkus** [comment]
@mvatansever any particular reason you decided to stay on 2.8.2 rather than upgrade to 2.9.x?

**Comment by weierophinney** [comment]
I've created a 2.8.4 release that includes the fixes from #168, which address the issue in the 2.9 series.

Since the 2.9 series _requires_ an upgraded zend-stdlib (2.9 requires zend-stdlib v3, whereas 2.8 allowed v2 releases), this seems like a sensible solution.

**Comment by mvatansever** [comment]
@Xerkus yes, we have another dependency which depends on 2.8 version. I don't understand the semantic versioning how to avoid to release a new patch version?

**Comment by froschdesign** [comment]
@mvatansever 
> …we have another dependency which depends on 2.8 version.

Can you explain this in more detail? Thanks!

> I don't understand the semantic versioning…

All informations can be found under https://semver.org

**Comment by mvatansever** [comment]
@froschdesign

> Can you explain this in more detail? Thanks!

This package's 2.9 version depend on zend-stdlib v3 version but the 2.8 version depend on v2. The exact same issue described by @weierophinney .

> All informations can be found under https://semver.org

Also, I don't see any problem and obstacle to release a new patch version by the approach of semver. I think it can be a patch version just fixed the bug like what did @weierophinney. Thanks again.

**Comment by froschdesign** [comment]
@mvatansever 
Please don't get me wrong, I'm not against your request or the idea to support an older of version.
I wanted to clarify the "another dependency" and "I don't understand the semantic versioning".
No more, no less. 😃

**Comment by mvatansever** [comment]
@froschdesign the full sentence is more meaningful 😃 
> I don't understand the semantic versioning **how to avoid to release a new patch version?**

So we clarified each other with successfully 😄

**Comment by weierophinney** [comment]
> Also, I don't see any problem and obstacle to release a new patch version by the approach of semver. I think it can be a patch version just for fixing this bug. Thanks again @weierophinney.

This was a **special case**.

The bug was introduced in a patch release, and we then immediately did a minor release. Typically, you can upgrade to minor releases without problems. However, in this particular case, we bumped the minimum required version of a dependency to a new _major_ version, which is something that you often cannot update to using `composer update` without making changes to your application `composer.json` or first removing the `composer.lock` and `vendor/` subdirectory.

In terms of obstacles to releasing a new patch, it can range from trivial to incredibly difficult, based on what changes happened to create the new minor release. If we have released the minor version in a way that developers can upgrade without problems, we **will not** backport patches.
