### ISSUE TITLE
Implement SameSite directive for SetCookie

### ISSUE THREAD

**Issue by jroedel** [zendframework/zend-http#174]
I would like to use the [SameSite directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) when setting cookies in ZF3, but there doesn't seem to be an option to do so.

This should be a 10th parameter for the SetCookie constructor I guess.

### Code to reproduce the issue (example constructor call)

```php
$setCookie = new SetCookie($cookieName, $locale, null, $path, null, $secure, $httpOnly, $maxAge, $version, SetCookie::SAME_SITE_STRICT);
```

### Expected results

This should set a cookie with the indicated SameSite directive

### Actual results

Doesn't allow for specification

**Comment by carnage** [comment]
A possible temp band aid solution might look like:
```
        $cookie = new class(
//cookie options
        ) extends SetCookie {
            public function getFieldValue()
            {
                return parent::getFieldValue() . '; SameSite=lax';
            }
        };
```
