### ISSUE TITLE
"Invalid status code provided" while processing the Http Response

### ISSUE THREAD

**Issue by roypalacios** [zendframework/zend-http#178]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-http/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-http/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Issue #27 should be reopened.

This is 2019 and we should not fail to parse a response just because the HTTP Status is not strictly standard.

Adding a custom HTTP status is not an option if we are dealing with external Http servers. In my case I'm getting a 520.

### Code to reproduce the issue

Response.php

```php

    /**
     * Set HTTP status code and (optionally) message
     *
     * @param  int $code
     * @throws Exception\InvalidArgumentException
     * @return self
     */
    public function setStatusCode($code)
    {
        $const = get_class($this) . '::STATUS_CODE_' . $code;
        if (! is_numeric($code) || ! defined($const)) {
            $code = is_scalar($code) ? $code : gettype($code);
            throw new Exception\InvalidArgumentException(sprintf(
                'Invalid status code provided: "%s"',
                $code
            ));
        }

        return $this->saveStatusCode($code);
    }

```

### Expected results

- Treat anything >= 600 as a 500 - Internal Server Error
- Accept any 5xx
- Accept any 4xx
- Accept any 3xx
- Accept any 2xx as OK
- No change to 1xx

### Actual results

Zend-Http is able to understand "I'm a teapot"  but unable to process LOTs of valid responses coming from a myriad of sources.

This really needs to be fixed. Otherwise people will accelerate the move out of Zend altogether.

Please let me know if you are willing to accept this issue, and need help implementing it.

**Comment by Ocramius** [comment]
> This is 2019 and we should not fail to parse a response just because the HTTP Status is not strictly standard.

That's not a helpful way to report issues: if you have a problem, send a patch with a test case, but writing "it should zomg why no fix yet?!" is not going to make you a lot of friends in OSS projects.

I'm pretty sure that we should not support anything above 599 anyway though, as [`zendframework/zend-diactoros` also enforces that](https://github.com/zendframework/zend-diactoros/blob/9a4b4a3c78c1a65e6096fb1f37ab424f33c68821/src/Response.php#L33)

**Comment by roypalacios** [comment]
Hi Ocramius

Thanks for reading.

I'm more than happy to submit a patch for this. But first I need the approvers to agree on a design or expected results.

**Comment by roypalacios** [comment]
Ok. No response from any maintainer. Good thing is I did not fix anything.

This seems to be abandonware. I will stop using zend-http, and as always try to get out of zend and PHP.

**Comment by MadCat34** [comment]
> Ok. No response from any maintainer. Good thing is I did not fix anything.
Nice state of mind ...

Maintainers have fulltime-job and family life, some are also involved in several open-source projects (like Ocramius; thanks for your job :+1: ) or go to events in the PHP community (as speakers or not).
They may not answer as fast as YOU would like...Be patient

> Zend-Http is able to understand "I'm a teapot" but unable to process LOTs of valid responses coming from a myriad of sources.
Not strictly valid since HTTP code 520 itself is not documented by any of the HTTP specifications...

 >  I will stop using zend-http, and as always try to get out of zend and PHP.
It's not a problem proper to Zend Framework nor PHP...

**Comment by roypalacios** [comment]
Hi MadCat34,

Let's try to solve this issue.

**zend-diactoros:** https://github.com/zendframework/zend-diactoros/blob/9a4b4a3c78c1a65e6096fb1f37ab424f33c68821/src/Response.php#L170

**zend-http:** https://github.com/zendframework/zend-http/blob/master/src/Response.php#L280

We need to make zend-http behave exactly like zend-diactoros:
- setStatusCode should only throw an exception is the http status code is < 100 or > 599

Please note, the standard defines ranges, but from my understanding it doesn't prohibit anything like 520 or 555.

**Comment by roypalacios** [comment]
If you guys are willing to accept this change, I'm fine to write the code and few tests.

**Comment by Ocramius** [comment]
The approach is fine: send a patch with a failing test case and the fix for it, and it will most likely be merged.

Also, as @MadCat34 said, OSS is not my full-time job: I do this when I have time and the mood for it.

**Comment by webimpress** [comment]
@roypalacios Are you willing to submit your PR?

**Comment by roypalacios** [comment]
Hi @webimpress,

Yes, I can submit it in the next few days!

**Comment by roypalacios** [comment]
Hello @webimpress @Ocramius @MadCat34 

Please review the pull request -> https://github.com/zendframework/zend-http/pull/194

I have modified the code so that it behaves just as diactoros in this sense.

**zend-diactoros:** https://github.com/zendframework/zend-diactoros/blob/9a4b4a3c78c1a65e6096fb1f37ab424f33c68821/src/Response.php#L170

If anything else is needed, please let me know.

Roy
