### ISSUE TITLE
empty header values in responses are breaking the application since version 2.10.1

### ISSUE THREAD

**Issue by BigMichi1** [zendframework/zend-http#202]
- [ x ] I was not able to find an [open](https://github.com/zendframework/zend-http/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-http/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ x ] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

since the update from version 2.10.0 to 2.10.1 (only this package changed) i receive this error ``Zend\Diactoros\Exception\InvalidArgumentException: Invalid header value type; must be a string or numeric; received NULL`` when i'm using the geocoder module. i tracked it down to this request that is sent: https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?text=Alexanderplatz%2C+Berlin&sourceCountry=DEU&maxLocations=1&f=json&outFields=*

in the response the header field for ``Server`` is empty, see:
![Screenshot_20191203_101956](https://user-images.githubusercontent.com/91786/70037502-eea14900-15b6-11ea-91b7-ebb26cc75cdd.png)

### Expected results

should not fail on empty header values, like it was in version 2.10.0

### Actual results

request are failing because of the response contains an empty header value

**Comment by michalbundyra** [comment]
@BigMichi1 Thanks for reporting. I would need more details. Exception from Diactoros is not helpful, as zend-http doesn't have that dependency and it must be somewhere in your project.

**Comment by weierophinney** [comment]
@BigMichi1 Are you using zend-psr7bridge by any chance?

**Comment by BigMichi1** [comment]
i'm using also 
``zendframework/zend-psr7bridge                1.2.0               PSR-7 &lt;-&gt; zend-http message conversions``
thats right, the issue is before updating zend-http to 2.10.1 it works with version 2.10.0

**Comment by michalbundyra** [comment]
@BigMichi1 Version 2.11.1 with the hotfix has been released. Thanks for reporting the issue!
