### ISSUE TITLE
Custom HTTP status codes invalid

### ISSUE THREAD

**Issue by jeanCarloMachado** [zendframework/zend-http#27]
I'm having problem when trying to use a custom status code: 419 with zend-http.

The error:
```
Fatal error: Uncaught exception 'Zend\Http\Exception\InvalidArgumentException' with message 'Invalid status code provided: "419"' in /home/jean/projects/clipp/Backend/vendor/zendframework/zend-http/src/Response.php:254
Stack trace:
#0 /home/jean/projects/clipp/Backend/module/Api/Module.php(96): Zend\Http\Response->setStatusCode(419)
```

**Comment by jeanCarloMachado** [comment]
I thought It would be better to enable the usage of custom status. Maybe through the activation of a parameter.

**Comment by Martin-P** [comment]
> I thought It would be better to enable the usage of custom status. Maybe through the activation of a parameter.

Already possible, see method [`Zend\Http\Response::setCustomStatusCode`](https://github.com/zendframework/zend-http/blob/84fcb5c02fb5144b249246e978a43694f8dabeab/src/Response.php#L273-L291).
