### ISSUE TITLE
setUri() invalidates relative URI when setting default ports

### ISSUE THREAD

**Issue by antiphp** [zendframework/zend-http#36]
Hi,

when setting a relative URI `/example` the `Zend\Http\Client::setUri()` method adds a default port and so invalidates the URI resulting in isValidRelative() returning FALSE instead of TRUE.

``` php
<?php
require './vendor/autoload.php';
$relativeUri = '/example';
$client = new Zend\Http\Client($relativeUri);
$uri = new Zend\Uri\Http($relativeUri);
var_dump($client->getUri()->isValidRelative(), $uri->isValidRelative());
```

_Expected output_

```
boolean(true)
boolean(true)
```

_Actual output_

```
boolean(false)
boolean(true)
```

I don't know how to build a patch, but line 323 of `Client.php` should be
`if (! $this->getUri()->getPort() && $this->getUri()->isAbsolute()) {`
instead of
`if (! $this->getUri()->getPort()) {`

Cheers

**Comment by samsonasik** [comment]
@antiphp I've created PR https://github.com/zendframework/zend-http/pull/149 for it
