### ISSUE TITLE
Redirects counter

### ISSUE THREAD

**Issue by Ragazzo** [zendframework/zend-http#4]
Currently in code there is a hard coded `do-while` construction that does not allow to perform request without having any redirects. I think it is better to allow developer to configure this option, since if i set it to `0` that means no redirects it will not affect [current code](https://github.com/zendframework/zend-http/blob/master/src/Client.php#L977). If needed i can submit PR.

**Comment by adamlundrigan** [comment]
You should be able to set the option `maxredirects` to -1 to achieve this.
