### ISSUE TITLE
Curl Adapter Needs to Look for Case Insensitive Headers

### ISSUE THREAD

**Issue by KarunaGovind** [zendframework/zend-http#50]
\Zend\Http\Client\Adapter\Curl removes a few response headers (namely Transfer-Encoding, Content-Encoding) to make sure \Zend\Http\Response behaves correctly.

However, it assumes response headers have fixed cases. The AWS ELB in particular returns "transfer-encoding" as all lower case, therefore the code needs to do a case insensitive replace.

**Comment by rsacksteder** [comment]
Ran into this exact same issue! Hopefully this can be reviewed and pulled into the next release.

**Comment by samsonasik** [comment]
can be closed as it seems fixed at https://github.com/zendframework/zend-http/pull/53
