### ISSUE TITLE
Add verify_peer_name option to Socket Adapter

### ISSUE THREAD

**Issue by monkeyphp** [zendframework/zend-http#52]
I've had problems sending requests to a local dev server which has a self signed certificate which does not match the domain name.

I've found that setting the `verify_peer_name` option to false (http://php.net/manual/en/context.ssl.php#context.ssl.verify-peer) works around this issue - but there is no way to pass this as an option to the Socket adapter.

It may be that this option is not available by design - for security reasons perhaps - but I don't know.

I cannot find any reason why this feature cannot be added to the code - and would be happy to work on this and raise a PR.

**Comment by P0rnflake** [comment]
+1 this may also relates to #82

**Comment by Xerkus** [comment]
It was implemented in #32 and released with 2.6
