### ISSUE TITLE
Incorrect handling of negative MaxAge cookie attribute

### ISSUE THREAD

**Issue by milesich** [zendframework/zend-http#55]
Currently cookies with negative Max-Age attribute will throw en exception. But according to [RFC6265](http://www.ietf.org/rfc/rfc6265.txt):

>  If the first character of the attribute-value is not a DIGIT or a "-" character, ignore the cookie-av.

I found this problem when I was trying to import a feed using `Zend\Feed\Reader\Reader::import` and in the feed headers was this cookie:

`Set-Cookie: wpSGCacheBypass=0; expires=Fri, 15-Apr-2016 07:10:31 GMT; Max-Age=-3600; path=/`

**Comment by Xerkus** [comment]
Fixed in #120
