### ISSUE TITLE
Call to undefined method Zend\Http\Response::extractCode

### ISSUE THREAD

**Issue by neilime** [zendframework/zend-http#6]
Hi,

Zend\Http\Client\Adapter\Proxy is calling an undefined method, how could it works ?

https://github.com/zendframework/zend-http/blob/master/src/Client/Adapter/Proxy.php#L247

**Comment by Maks3w** [comment]
Fixed https://github.com/zendframework/zend-http/commit/886274e4176c42daa6515712e39fd3d62bc4afe6
