### ISSUE TITLE
Add method to check that status code is correct

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-http#75]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://github.com/zendframework/zendframework/issues/7260
User: @snapshotpl
Created On: 2015-02-25T19:04:41Z
Updated At: 2015-03-19T20:17:42Z
Body

---
### Comment

User: @weierophinney
Created On: 2015-02-26T17:32:46Z
Updated At: 2015-02-26T17:32:46Z
Body
Rebase this against current develop branch, please.

---
### Comment

User: @snapshotpl
Created On: 2015-02-26T17:53:07Z
Updated At: 2015-02-26T18:09:07Z
Body
I think a little about this and static method will be better. What are you think?

---
### Comment

User: @snapshotpl
Created On: 2015-03-02T21:09:38Z
Updated At: 2015-03-02T21:09:38Z
Body
@weierophinney done

---

**Comment by michalbundyra** [comment]
No longer needed. Since 2.11.0 we consider any status code between 100 and 599 (inclusive) as valid.
