### ISSUE TITLE
Http/Header/Cookie Uncaught exception

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-http#77]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7197
User: @Moring
Created On: 2015-02-09T22:51:11Z
Updated At: 2016-03-24T06:58:00Z
Body
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'urlencode() expects parameter 1 to be string, array given' in /home/www/vendor/zendframework/zendframework/library/Zend/Http/Header/Cookie.php:93

referer: http://search.daum.net/

Perhaps add check to $value or graceful catch?

---
### Comment

User: @jaapio
Created On: 2015-02-10T19:15:15Z
Updated At: 2015-02-10T19:15:15Z
Body
I agree with you that this could be nicer, but I'm not sure if you should set any thing else then a scalar value in a Cookie Header. If I understand the rfc about cookies correctly you should use the set-cookie header for this purpose.

---
### Comment

User: @Moring
Created On: 2015-02-10T20:18:59Z
Updated At: 2015-02-10T20:18:59Z
Body
The issue is that the query, when sent to a ZF2 application, triggers an unhandled fatal error.  To me, this can easily become (or is) a penetration test.  It should be handled more gracefully than a fatal error.

---
### Comment

User: @andsol
Created On: 2016-03-24T06:56:34Z
Updated At: 2016-03-24T06:58:00Z
Body
Similar issue, server log full of these errors.

PHP Error: 1: urlencode() expects parameter 1 to be string, array given. File: ...../vendor/zendframework/zend-http/src/Header/Cookie.php, in 101 line.

---

**Comment by tflori** [comment]
open #92 to solve this problem

**Comment by tflori** [comment]
@GeeH I have solved this issue with PR #92 please review it. thx

**Comment by ezimuel** [comment]
@tflori I commented about #92, waiting your reply. Thanks!

**Comment by Xerkus** [comment]
Was this issue fixed by the PR?

**Comment by tflori** [comment]
@icanhazstring can you check if #92 solves this issue?

**Comment by Moring** [comment]
Have not seen this error in the last month of logs, we end to end latest ZF3, so for us, it is fixed.

**Comment by Xerkus** [comment]
thanks
