### ISSUE TITLE
Zend/Http/Client/Adapter/Socket - options for stream context

### ISSUE THREAD

**Issue by igor-astsakhov** [zendframework/zend-http#82]
It is not possible to specify options for the stream context, in php 7 there seems to be something strict on the self signed certificates and peer/host must verify.  Providing         'ssl' => array(  
            'verify_host' => false,  
            'verify_peer' => false,  
        ),  options by passes the check and allows the socket creation, without those options it fails and throws an exception. 

If its possible to add the ability to pass the options via config like the local_cert and passphrase would be great.

**Comment by P0rnflake** [comment]
+1

**Comment by webimpress** [comment]
@igor-astsakhov  @NiMeDia It seems to be resolved already as I can see options: `sslpassphrase` (for `passphrase`) and `sslcert` (for `local_cert`) in `Socket` adapter.
